version: '3.7'
services:
  react:
    build: ./front
    container_name: front
    tty: true
    volumes:
      - ./front/src:/app
    ports:
      - "5173:5173"

  fast_api:
    build:
      context: ./backend/api
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    volumes:
      - ./backend/db/init:/docker-entrypoint-initdb.d
      - ./backend/db/data:/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    ports:
      - "5432:5432"